add tensorflow-addons
drivendataorg/noaa-runtime pull request #7
Opened 2021-01-12 07:53 UTC by Fissium

add tensorflow-addons=0.12.0

2021-01-13 09:23 UTC, marcalph commented
Hi Fissium,
IMO in `test_installs.py` it should be tnsorflow_addons

2021-01-14 10:05 UTC, marcalph commented
OK scratch that, it looks like conda doesn't have a great support for tf addons.. Maybe add a different channel?

2021-01-14 13:53 UTC, isms commented
@cszc Request your review on this one

2021-01-14 16:27 UTC, cszc requested changes

2021-01-14 16:27 UTC, cszc commented on runtime/py.yml
> -  - pytorch-lightning=1.1.2
@Fissium Can you add a new line here for `tensorflow-addons` instead of replacing the line for `pytorch-lightning`?

2021-01-20 15:38 UTC, cszc commented
@Fissium do you still need this merged?

2021-01-20 17:50 UTC, Fissium commented
Hi @cszc,
Yes, I still want to add the package to the runtime, but I don't quite understand what needs to be done. 
Can you explain to me?

2021-01-20 18:24 UTC, merged

2021-01-20 18:25 UTC, cszc commented
@Fissium no worries! I made the change directly. You should be all set now.

2021-01-21 07:20 UTC, Fissium commented
@cszc Thank you very much)